export const Cities = [
    //{ 不限縣市: '' },
    { 臺北市: 'Taipei' },
    { 新北市: 'NewTaipei' },
    { 桃園市: 'Taoyuan' },
    { 新竹市: 'Hsinchu' },
    { 新竹縣: 'HsinchuCounty' },
    { 臺中市: 'Taichung' },
    { 彰化縣: 'ChanghuaCounty' },
    { 南投縣: 'NantouCounty' },
    { 雲林縣: 'YunlinCounty' },
    { 嘉義市: 'Chiayi' },
    { 嘉義縣: 'ChiayiCounty' },
    { 臺南市: 'Tainan' },
    { 高雄市: 'Kaohsiung' },
    { 屏東縣: 'PingtungCounty' },
    { 基隆市: 'Keelung' },
    { 宜蘭縣: 'YilanCounty' },
    { 花蓮縣: 'HualienCounty' },
    { 台東縣: 'TaitungCounty' },
    { 金門縣: 'KinmenCounty' },
    { 澎湖縣: 'PenghuCounty' },
    { 連江縣: 'LienchiangCounty' },
];
export const CitiesZh = {
    Taipei: '臺北市',
    NewTaipei: '新北市',
    Taoyuan: '桃園市',
    Hsinchu: '新竹市',
    HsinchuCounty: '新竹縣',
    Taichung: '臺中市',
    ChanghuaCounty: '彰化縣',
    NantouCounty: '南投縣',
    YunlinCounty: '雲林縣',
    Chiayi: '嘉義市',
    ChiayiCounty: '嘉義縣',
    Tainan: '臺南市',
    Kaohsiung: '高雄市',
    PingtungCounty: '屏東縣',
    Keelung: '基隆市',
    YilanCounty: '宜蘭縣',
    HualienCounty: '花蓮縣',
    TaitungCounty: '台東縣',
    KinmenCounty: '金門縣',
    PenghuCounty: '澎湖縣',
    LienchiangCounty: '連江縣',
};

// export const Citys={
//     "台北市":"Taipei",
//     "臺北市":"Taipei",
//     "新北市":"NewTaipei",
//     "桃園市":"Taoyuan",
//     "台中市":"Taichung",
//     "臺中市":"Taichung",
//     "台南市":"Tainan",
//     "臺南市":"Tainan",
//     "高雄市":"Kaohsiung",
//     "基隆市":"Keelung",
//     "連江縣":"LienchiangCounty"
// };
